### PR TITLE
Added Retina Fake App Icons to Projects 

### PR DESCRIPTION
**Pull request by ljuba**
Also updated non-retina images to model app icons (e.g. Voice Memos)

### CODE REVIEW

**Comment by lorenbrichter** [comment]
Huge! Thanks! Would you mind removing the _xcuserdatad_ dirs from the commit?

**Comment by ljuba** [comment]
Oh, duh. Of course.

**Comment by jwilling** [comment]
Thanks so much for this!

**Comment by ljuba** [comment]
No problem. How's this project coming along otherwise? Like the ability to replace "Carrier" in the status bar.

**Pull request merged**
